# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 247d65344b174474b6e010238d63fb631fdb6cca0368b1a4fb7ff137ae5a8080bacbe6bb976cebc98b611cef9fcfcb6274496d99a7dd9a6dc94688bff83b639c

test:
  secret_key_base: 0d756b377d91a36149de84ef26813dfa4429596b3a78c535088e1538708e77fea6268ca219dea5af1a381eeaffb659521e97067f6da1ff3d2b820160943be6fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
